
package br.com.banco;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BancoWebServiceImplService", targetNamespace = "http://banco.com.br/", wsdlLocation = "http://127.0.0.1:4001/banco?wsdl")
public class BancoWebServiceImplService
    extends Service
{

    private final static URL BANCOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANCOWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BANCOWEBSERVICEIMPLSERVICE_QNAME = new QName("http://banco.com.br/", "BancoWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:4001/banco?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANCOWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BANCOWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BancoWebServiceImplService() {
        super(__getWsdlLocation(), BANCOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BancoWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANCOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BancoWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BANCOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BancoWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANCOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BancoWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BancoWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BancoWebService
     */
    @WebEndpoint(name = "BancoWebServiceImplPort")
    public BancoWebService getBancoWebServiceImplPort() {
        return super.getPort(new QName("http://banco.com.br/", "BancoWebServiceImplPort"), BancoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BancoWebService
     */
    @WebEndpoint(name = "BancoWebServiceImplPort")
    public BancoWebService getBancoWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://banco.com.br/", "BancoWebServiceImplPort"), BancoWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANCOWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BANCOWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BANCOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
