
package br.com.banco;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BancoWebService", targetNamespace = "http://banco.com.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BancoWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://banco.com.br/BancoWebService/criaNovaContaRequest", output = "http://banco.com.br/BancoWebService/criaNovaContaResponse")
    public void criaNovaConta(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.banco.Conta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://banco.com.br/BancoWebService/saldoRequest", output = "http://banco.com.br/BancoWebService/saldoResponse")
    public Conta saldo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.banco.TransacaoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://banco.com.br/BancoWebService/extratoRequest", output = "http://banco.com.br/BancoWebService/extratoResponse")
    public TransacaoArray extrato(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://banco.com.br/BancoWebService/depositoRequest", output = "http://banco.com.br/BancoWebService/depositoResponse")
    public boolean deposito(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://banco.com.br/BancoWebService/saqueRequest", output = "http://banco.com.br/BancoWebService/saqueResponse")
    public boolean saque(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1);

}
